name: Release

on:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: self-hosted

    container:
      image: alpine/git

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Building assets
        run: echo "REPLACE ME!" > assets.txt

      # - name: Set output
      #   id: vars
      #   run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: upload asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: assets.txt
