name: Release

on:
  release:
    types:
      - published

jobs:
  build-asset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.30/earthly-${{matrix.os}}-${{matrix.arch}} -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

      - name: Build Assets
        run: earthly +libphonenumber --platform=${{matrix.os}}/${{matrix.arch}}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber ${{ steps.vars.outputs.tag }} "cpp/build/assets_${{matrix.os}}_${{matrix.arch}}.zip"
